name: Tests
on:
  pull_request_target:
  push:
    branches:
      - main

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: "build: checkout"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: "build: install dependencies"
        run: npm ci

      - name: "build: build"
        run: npm run build

      - name: "build: test"
        run: npm test
